DROP DATABASE IF EXISTS sfmeets;
CREATE DATABASE sfmeets;

USE sfmeets;

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD BINARY(60) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS EVENTS;
CREATE TABLE EVENTS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    DATE VARCHAR(50) NOT NULL,
    TIME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ORGS;
CREATE TABLE ORGS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO ACCOUNT (USERNAME, PASSWORD, EMAIL, FIRSTNAME, LASTNAME)
VALUES
('admin', 'admin', 'admin@admin.com', 'admin', 'admin'),
('testuser', 'test', 'tester@tester.org', 'test', 'user');

INSERT INTO EVENTS (NAME, LOCATION, DATE, TIME, DESCRIPTION)
VALUES
('testevent', 'testlocation', 'testdate', 'testtime', 'testdescription');

INSERT INTO ORGS (NAME, DESCRIPTION)
VALUES
('testorg', 'testdescription');
